// packages/codegen/src/generate.ts
// Generates artifacts from the @lakshya/core resource registry:
//   - zod schemas (mirror validation.ts, but emitted as standalone code)
//   - TS interfaces for each resource
//   - OpenAPI 3 spec
//   - typed fetch client
// One resource definition => many consumer artifacts (closes the metadata loop).

import { registry, type Resource, type Field } from '@lakshya/core';

function tsType(field: Field): string {
  switch (field.type) {
    case 'uuid':
    case 'string':
    case 'text':
    case 'richtext':
    case 'enum':
    case 'date':
    case 'datetime':
    case 'relation':
    case 'media':
      return 'string';
    case 'int':
    case 'float':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'tags':
      return 'string[]';
    case 'json':
    case 'computed':
    case 'virtual':
      return 'unknown';
    default:
      return 'unknown';
  }
}

function zodExpr(field: Field): string {
  let base: string;
  switch (field.type) {
    case 'int':
      base = 'z.number().int()';
      break;
    case 'float':
      base = 'z.number()';
      break;
    case 'bool':
      base = 'z.boolean()';
      break;
    case 'enum':
      if (field.options && !Array.isArray(field.options)) {
        base = `z.enum(${JSON.stringify(Object.keys(field.options))} as [string, ...string[]])`;
      } else base = 'z.string()';
      break;
    case 'tags':
      base = 'z.array(z.string())';
      break;
    case 'json':
    case 'computed':
    case 'virtual':
      base = 'z.any()';
      break;
    default:
      base = 'z.string()';
  }
  const v = field.validate ?? {};
  if ((field.type === 'string' || field.type === 'text' || field.type === 'richtext') && typeof v.min === 'number')
    base += `.min(${v.min})`;
  if ((field.type === 'string' || field.type === 'text' || field.type === 'richtext') && typeof v.max === 'number')
    base += `.max(${v.max})`;
  if (v.email) base += '.email()';
  return base;
}

export function genZod(resource: Resource): string {
  const lines: string[] = [];
  for (const [key, field] of Object.entries(resource.fields)) {
    if (field.generated) continue;
    const required = field.required?.includes('create') ?? false;
    const expr = zodExpr(field) + (required ? '' : '.optional()');
    lines.push(`  ${key}: ${expr},`);
  }
  return `export const ${resource.name}CreateSchema = z.object({\n${lines.join('\n')}\n});\n`;
}

export function genTypes(resource: Resource): string {
  const lines: string[] = [];
  for (const [key, field] of Object.entries(resource.fields)) {
    const opt = field.generated || (field.required ? !field.required.includes('create') : true) ? '?' : '';
    lines.push(`  ${key}${opt}: ${tsType(field)};`);
  }
  return `export interface ${cap(resource.name)} {\n${lines.join('\n')}\n}\n`;
}

export function genOpenAPI(resources: Resource[]): any {
  const paths: Record<string, any> = {};
  const schemas: Record<string, any> = {};
  for (const r of resources) {
    const props: Record<string, any> = {};
    for (const [key, field] of Object.entries(r.fields)) {
      props[key] = { type: tsType(field) === 'number' ? 'number' : tsType(field) === 'boolean' ? 'boolean' : 'string' };
    }
    schemas[cap(r.name)] = { type: 'object', properties: props };
    paths[`/api/${r.name}`] = {
      get: { summary: `List ${r.labelPlural ?? r.label}`, responses: { '200': { description: 'ok' } } },
      post: { summary: `Create ${r.label}`, responses: { '201': { description: 'created' } } },
    };
    paths[`/api/${r.name}/{id}`] = {
      get: { summary: `Get ${r.label}` },
      patch: { summary: `Update ${r.label}` },
      delete: { summary: `Delete ${r.label}` },
    };
  }
  return {
    openapi: '3.0.0',
    info: { title: 'Lakshyanew API', version: '0.1.0' },
    paths,
    components: { schemas },
  };
}

export function genClient(resources: Resource[]): string {
  const methods: string[] = [];
  for (const r of resources) {
    const C = cap(r.name);
    methods.push(`  list${C}s(token: string, q?: Record<string, any>) { return request('GET', '/api/${r.name}', token, undefined, q); }`);
    methods.push(`  get${C}(token: string, id: string) { return request('GET', \`/api/${r.name}/\${id}\`, token); }`);
    methods.push(`  create${C}(token: string, body: Partial<${C}>) { return request('POST', '/api/${r.name}', token, body); }`);
    methods.push(`  update${C}(token: string, id: string, body: Partial<${C}>) { return request('PATCH', \`/api/${r.name}/\${id}\`, token, body); }`);
    methods.push(`  delete${C}(token: string, id: string) { return request('DELETE', \`/api/${r.name}/\${id}\`, token); }`);
  }
  const typeNames = resources.map((r) => cap(r.name)).join(', ');
  return `// AUTO-GENERATED by @lakshya/codegen — do not edit by hand.
import type { ${typeNames} } from './types.js';
export interface ApiEnvelope<T> { status: number; data: T; message: string; }

async function request(method: string, path: string, token: string, body?: any, q?: Record<string, any>) {
  const url = new URL(path, 'http://localhost');
  if (q) for (const [k, v] of Object.entries(q)) url.searchParams.set(k, String(v));
  const res = await fetch(url.pathname + url.search, {
    method, headers: { authorization: 'Bearer ' + token, 'content-type': 'application/json' }, body: body ? JSON.stringify(body) : undefined,
  });
  return res.json();
}

export const api = {
${methods.join(',\n')}
};
`;
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export interface GeneratedArtifacts {
  zod: string;
  types: string;
  openapi: any;
  client: string;
}

export function generateAll(): GeneratedArtifacts {
  const resources = registry.all();
  const zod = resources.map(genZod).join('\n');
  const types = resources.map(genTypes).join('\n');
  const openapi = genOpenAPI(resources);
  const client = genClient(resources);
  return { zod, types, openapi, client };
}
